# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=com.igrium.craftui
archives_base_name=craftui

# Dependencies
fabric_version=0.161.0+26.3
imgui_version=26.3-1.2.0+imgui.1.92.7.1
imgui_java_version=1.92.7.1
modmenu_version=21.0.0-beta.1
