# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.igrium.craftui
archives_base_name=craftui

# Dependencies
fabric_version=0.155.2+26.2
imgui_version=26.2-1.1.0+imgui.1.92.0
modmenu_version=20.0.1
